apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    machine.openshift.io/GPU: '0'
    machine.openshift.io/memoryMb: '16384'
    machine.openshift.io/vCPU: '4'
  name: ocp4-dubai-f13f-ipi-7hlhp-worker-eastus23
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: ocp4-dubai-f13f-ipi-7hlhp
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp4-dubai-f13f-ipi-7hlhp
      machine.openshift.io/cluster-api-machineset: ocp4-dubai-f13f-ipi-7hlhp-worker-eastus23
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp4-dubai-f13f-ipi-7hlhp
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp4-dubai-f13f-ipi-7hlhp-worker-eastus23
    spec:
      metadata: {}
      providerSpec:
        value:
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: ocp4-dubai-f13f-ipi-7hlhp-rg
          publicLoadBalancer: ocp4-dubai-f13f-ipi-7hlhp
          userDataSecret:
            name: worker-user-data
          vnet: ocp4-dubai-f13f-ipi-7hlhp-vnet
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: '3'
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: ocp4-dubai-f13f-ipi-7hlhp-rg
          kind: AzureMachineProviderSpec
          location: eastus2
          vmSize: Standard_D4s_v3
          image:
            offer: ''
            publisher: ''
            resourceID: >-
              /resourceGroups/ocp4-dubai-f13f-ipi-7hlhp-rg/providers/Microsoft.Compute/images/ocp4-dubai-f13f-ipi-7hlhp
            sku: ''
            version: ''
          managedIdentity: ocp4-dubai-f13f-ipi-7hlhp-identity
          subnet: ocp4-dubai-f13f-ipi-7hlhp-worker-subnet
          apiVersion: azureproviderconfig.openshift.io/v1beta1
